### ISSUE TITLE
Cannot download latest build.

### ISSUE THREAD

**Issue by deligoez** [DIYBookScanner/spreadpi#37]
Hi there,

I can't download latest build. The server seems to be not responding.
Anything to do?

Thanks.

**Comment by duerig** [comment]
Unfortunately, Spreads has been not been maintained for some time.



For your purposes, I'm not sure how much it will help since much of the
camera-handling code is very similar to Pi Scan (Pi Scan was originally
based on the core of Spreads). A better option to try that might reveal
the problem you are having is TwoCamControl which runs on windows. See
the forum thread here:


https://diybookscanner.org/forum/viewtopic.php?f=20&t=3082



However, I do want to point people to a living link to a Spreads build.
I do not know if it is the absolute latest, but the stable version of
Spreads that I last used is here:


http://tenrec.builders/pi/archivist-2m.zip



Please note that this version is likely to be unstable on Pi 2 and Pi 3
since the base drivers are pretty old at this point. I'd try running it
on a Pi B+.


---

Jonathon Duerig

Tenrec Builders LLC





On Fri, Jan 13, 2017, at 02:30 PM, Yunus Emre Deligöz wrote:

> Hi there,



> I can't download latest build. The server seems to be not responding.
>  Anything to do?



> Thanks.



> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 




Links:

  1. https://github.com/DIYBookScanner/spreadpi/issues/37

**Comment by deligoez** [comment]
Thanks for reply again duerig,

If you remember, we had problems with piscan. we replaced the pi, cables and sd cards. 
Without using the ac adaptors it seems to work. But now we have focus issues. Everytime only one camera seems to be blurry.

Do have any checklist for this problem 😄 ?

Thanks again,

**Comment by duerig** [comment]
Well, there are a couple of possibilities. :-)



(1) Make sure that when you are taking the 'refocus' shots that you have
    the book open to a page that has text in the center of the shot.
    When it autofocuses, it can't really tell whether a blank page or
    mostly blank page is in focus or not. Or if the book is too small so
    that the center of the capture is the cradle, then the focus will be
    off by a few inches.


(2) Rarely, I have seen some cameras that lose their ability to
    autofocus after a random number of shots. Their internal state gets
    screwed up somehow and all pictures are blurry after that. This
    happens whether or not you are using CHDK. It is temporarily fixed
    with a restart of the camera. If you have such a camera, it is
    usable if you manage to refocus and lock focus before its internal
    state breaks. So in this case, the best thing would be to get set up
    for refocus, take that once. Verify that everything is good, then
    rely on the fact that Pi Scan locks.


But on the whole if one camera seems to always be failing, then test out
that one camera rigorously and be prepared to replace it.


This is getting a bit far afield of Spreads support, though. So
hopefully the above will work and if it doesn't, you can email me at
duerig at jonathonduerig dot com or post on the Pi Scan support threads
and I can see if I can come up with other suggestions.








On Fri, Jan 13, 2017, at 03:42 PM, Yunus Emre Deligöz wrote:

> Thanks for reply again duerig,



> If you remember, we had problems with piscan. we replaced the pi,
> cables and sd cards.
>  Without using the ac adaptors it seems to work. But now we have focus
>  issues. Everytime only one camera seems to be blurry.
> Do have any checklist for this problem 😄 ?



> Thanks again,



> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/DIYBookScanner/spreadpi/issues/37#issuecomment-272568016
